/**
 * File mirror: renders the suite's structured domains into human-readable
 * markdown at `$DSH_HOME/mirror/` (and the repository `.agents/` directory),
 * so the shared direction, memory, and codebase map stay readable outside the
 * structured store and without an MCP client. The mirror is a read-only
 * projection — the domains are the source of truth and are never written from
 * here.
 * @module dsh-coherence/src/mirror
 */

import { join } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import { writeFileAtomic } from '@deepseek-ai/dsh-atomic-write'
import { defaultDshHome } from '@deepseek-ai/dsh-home-paths'
import type { MirrorConfig } from './config.ts'

const MIRROR_MODE = 0o600

function header(title: string): string {
  return `# ${title}\n\n_Generated by dsh-coherence — source of truth is the structured store._\n`
}

/**
 * Render every mirror file from the live domains. Missing services produce no
 * file for their slice.
 * @param ctx - plugin context with the suite services.
 * @param root - the mirror root directory.
 * @returns `[path, content]` pairs to write.
 */
export function renderMirrorFiles(ctx: Context, root: string): Array<[string, string]> {
  const out: Array<[string, string]> = []

  const worklog = ctx.get('worklog')
  if (worklog !== undefined) {
    const direction = worklog.getActiveDirection()
    const entries = worklog.listEntries({}).slice(0, 50)
    const lines = [header('Work direction')]
    if (direction !== undefined) {
      lines.push(`**${direction.title}** — ${direction.objective}`)
      if (direction.constraints.length > 0) lines.push(`Constraints: ${direction.constraints.join('; ')}`)
    } else {
      lines.push('_No active direction set._')
    }
    lines.push('', '## Recent worklog')
    if (entries.length === 0) lines.push('_(empty)_')
    for (const entry of entries) lines.push(`- [${entry.kind}] ${entry.text}`)
    out.push([join(root, 'DIRECTION.md'), lines.join('\n') + '\n'])
  }

  const memory = ctx.get('memory')
  if (memory !== undefined) {
    const semantic = memory.list({ layer: 'semantic' })
    const lines = [header('Semantic memory')]
    if (semantic.length === 0) lines.push('_(empty)_')
    for (const claim of semantic) {
      const text = 'claim' in claim ? `${claim.subject}: ${claim.claim}` : 'content' in claim ? claim.content : ''
      lines.push(`- ${text}`)
    }
    out.push([join(root, 'memory-semantic.md'), lines.join('\n') + '\n'])

    const episodic = memory.list({ layer: 'episodic', state: 'active' }).slice(0, 50)
    const episodeLines = [header('Recent episodes')]
    if (episodic.length === 0) episodeLines.push('_(empty)_')
    for (const episode of episodic) {
      const summary = 'summary' in episode ? episode.summary : 'content' in episode ? episode.content : ''
      episodeLines.push(`- ${episode.agentType}: ${summary}`)
    }
    out.push([join(root, 'memory-episodic.md'), episodeLines.join('\n') + '\n'])
  }

  const codebaseMap = ctx.get('codebaseMap')
  if (codebaseMap !== undefined) {
    const nodes = codebaseMap.list({}).slice(0, 100)
    const lines = [header('Codebase map')]
    if (nodes.length === 0) lines.push('_(empty)_')
    for (const node of nodes) {
      const address = 'qualifiedName' in node ? node.qualifiedName : node.relativePath
      const summary = 'docSummary' in node ? node.docSummary : node.summary
      lines.push(`- ${address}: ${summary}`)
    }
    out.push([join(root, 'codebase-map.md'), lines.join('\n') + '\n'])
  }

  const transcript = ctx.get('transcript')
  if (transcript !== undefined) {
    const messages = transcript.query({ limit: 1000 })
    const byAgent = new Map<string, number>()
    for (const message of messages) byAgent.set(message.agentType, (byAgent.get(message.agentType) ?? 0) + 1)
    const lines = [header('Transcript coverage')]
    for (const [agent, count] of byAgent) lines.push(`- ${agent}: ${count} messages`)
    if (byAgent.size === 0) lines.push('_(empty)_')
    out.push([join(root, 'transcripts.md'), lines.join('\n') + '\n'])
  }

  return out
}

/**
 * Mount the mirror: subscribe to the suite's domains, debounce, and render.
 * @param ctx - plugin context with the suite services.
 * @param config - mirror settings.
 * @returns a disposer clearing the timer and listener.
 */
export function mountMirror(ctx: Context, config: MirrorConfig): () => void {
  const root = config.root ?? join(defaultDshHome(), 'mirror')
  const logger = ctx.logger('dsh-coherence')
  let timer: ReturnType<typeof setTimeout> | undefined
  const render = (): void => {
    for (const [path, content] of renderMirrorFiles(ctx, root)) {
      void writeFileAtomic(path, content, { mode: MIRROR_MODE }).catch((error: unknown) => {
        logger.warn(`mirror write failed for ${path}: ${error instanceof Error ? error.message : String(error)}`)
      })
    }
  }
  const debounced = (): void => {
    if (timer !== undefined) clearTimeout(timer)
    timer = setTimeout(render, config.debounceMs)
  }
  const disposeListener = ctx.on('domain/changed', (change) => {
    if (change.domain === 'transcript' || change.domain === 'memory'
      || change.domain === 'codebase_map' || change.domain === 'worklog') {
      debounced()
    }
  }, { global: true })
  render()
  return () => {
    if (timer !== undefined) clearTimeout(timer)
    disposeListener()
  }
}
